# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a68470a6f577f55efda59ed1c74436f2dcdf388b4e690ca31d851fba9b959401ec442fd73da4aee22e220771e7f2ec2cfcbae263e985e15b4f47c530c9cf90f8

test:
  secret_key_base: f22de5a63ee011b59fbfdfbfcdc3638a82b5b0fe25a6c72919673c4e67b2a6042fdd9d65dd2fb47d0f0a545d47cf7f16175116ddafe068e8825b35fd5e6a6198

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
